
services:
  - type: web
    name: free-fire-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
